local M = {}

local hl = require("eyes.utility").hl
local palette = require("eyes.palette").palette

M.setup = function()
	hl("NonText", { fg = palette.hex04 })
	hl("SpecialKey", { link = "NonText" })
	hl("ColorColumn", { bg = nil })
	hl("CurSearch", { link = "Search" })
	hl("Cursor", { fg = palette.hex00, bg = palette.hex10 })
	hl("lCursor", { link = "Cursor" })
	hl("CursorColumn", { link = "CursorLine" })
	hl("CursorLine", { bg = palette.hex01 })
	hl("Directory", { fg = palette.hex10 })
	hl("DiffAdd", { fg = palette.hex08 })
	hl("DiffChange", { fg = palette.hex06 })
	hl("DiffDelete", { fg = palette.hex04 })
	hl("DiffText", { fg = palette.hex08 })
	hl("TermCursor", { link = "Cursor" })
	hl("WinSeparator", { link = "Border" })
	hl("Folded", { fg = palette.hex10 })
	hl("FoldColumn", { fg = palette.hex10 })
	hl("SignColumn", { link = "Icon" })
	hl("IncSearch", { link = "Search" })
	hl("Substitute", { link = "Search" })
	hl("LineNr", { fg = palette.hex04 })
	hl("CursorLineNr", { fg = palette.hex10 })
	hl("MatchParen", { fg = palette.hex10, bg = palette.hex02 })
	hl("Normal", { fg = palette.hex10, bg = palette.hex00 })
	hl("NormalFloat", { link = "Normal" })
	hl("FloatBorder", { link = "Border" })
	hl("FloatTitle", { link = "Title" })
	hl("PMenu", { link = "Normal" })
	hl("PMenuSel", { link = "CursorLine" })
	hl("PmenuSbar", { bg = palette.hex01 })
	hl("PmenuThumb", { bg = palette.hex08 })
	hl("Question", { fg = palette.hex10 })
	hl("QuickFixLine", { link = "CursorLine" })
	hl("Search", { fg = palette.hex10, bg = palette.hex03 })
	hl("StatusLine", { fg = palette.hex10, bg = palette.hex00 })
	hl("StatusLineNC", { fg = palette.hex10, bg = palette.hex00 })
	hl("TabLine", { fg = palette.hex06, bg = palette.hex00 })
	hl("TabLineFill", { fg = palette.hex10, bg = palette.hex00 })
	hl("TabLineSel", { fg = palette.hex10, bg = palette.hex00, bold = true })
	hl("Title", { fg = palette.hex10, bold = true })
	hl("Visual", { bg = palette.hex02 })
	hl("WinBar", { fg = palette.hex10, bg = palette.hex00 })
	hl("WinBarNC", { fg = palette.hex10, bg = palette.hex00 })
	hl("ModeMsg", { fg = palette.hex10 })
	hl("MoreMsg", { fg = palette.hex10 })
	hl("MsgSeparator", { link = "Border" })
end

return M
