local palette = require("eyes.palette")

return {
	Normal = { fg = palette.hex10, bg = palette.hex00 },
	NormalNC = "Normal",
	ColorColumn = { bg = palette.hex01 },
	Directory = { fg = palette.hex08 },
	Folded = { fg = palette.hex08, bg = palette.hex01 },
	Question = { fg = "fg" },
	Title = { fg = "fg", bold = true },
	WinSeparator = "Border",

	NormalFloat = "Normal",
	FloatBorder = "Border",
	FloatFooter = { fg = "fg" },
	FloatTitle = "Title",

	Cursor = "Reverse",
	lCursor = "Cursor",
	CursorIM = "Cursor",
	TermCursor = "Cursor",
	TermCursorNC = "Cursor",
	CursorColumn = "ColorColumn",
	CursorLine = "ColorColumn",
	CursorLineNr = { fg = "fg" },
	CursorLineFold = { fg = "fg" },
	CursorLineSign = { fg = "fg" },
	QuickFixLine = "ColorColumn",

	LineNr = { fg = palette.hex04 },
	LineNrAbove = "LineNr",
	LineNrBelow = "LineNr",
	FoldColumn = { fg = "fg" },
	SignColumn = { fg = "fg" },

	LspCodeLens = "Dim",
	LspCodeLensSeparator = "Dim",
	LspInlayHint = "Dim",
	LspReferenceRead = "Highlight",
	LspReferenceText = "Highlight",
	LspReferenceWrite = "Highlight",
	LspSignatureActiveParameter = "Highlight",
	MatchParen = "Highlight",
	SnippetTabstop = "Highlight",

	MsgArea = { fg = "fg" },
	ModeMsg = { fg = "fg" },
	MoreMsg = { fg = "fg" },
	ErrorMsg = "DiagnosticError",
	WarningMsg = "DiagnosticWarn",
	MsgSeparator = "Border",

	Search = { fg = "fg", bg = palette.hex03 },
	CurSearch = "Search",
	IncSearch = "Search",
	Substitute = "Search",

	Pmenu = { fg = "fg" },
	PmenuSel = "ColorColumn",
	PmenuKind = "Pmenu",
	PmenuKindSel = "PmenuSel",
	PmenuExtra = "Pmenu",
	PmenuExtraSel = "PmenuSel",
	PmenuSbar = { bg = palette.hex01 },
	PmenuThumb = { bg = palette.hex03 },
	PmenuMatch = { bold = true },
	PmenuMatchSel = { bg = palette.hex01, bold = true },
	WildMenu = "ColorColumn",
	ComplMatchIns = "Dim",

	Visual = { bg = palette.hex02 },
	VisualNOS = "Visual",

	StatusLine = { fg = "fg", bg = "bg" },
	StatusLineNC = { fg = palette.hex06, bg = "bg" },
	StatusLineTerm = "StatusLine",
	StatusLineTermNC = "StatusLineNC",
	TabLine = "StatusLineNC",
	TabLineFill = "TabLine",
	TabLineSel = { fg = "fg", bold = true },
	WinBar = "StatusLine",
	WinBarNC = "StatusLineNC",

	NonText = "Dim",
	Conceal = "NonText",
	EndOfBuffer = "NonText",
	SpecialKey = "NonText",

	debugPC = "ColorColumn",
	debugBreakpoint = "Icon",
}
