---@meta

---@class eyes.Palette
---@field hex00 string?
---@field hex01 string?
---@field hex02 string?
---@field hex03 string?
---@field hex04 string?
---@field hex05 string?
---@field hex06 string?
---@field hex07 string?
---@field hex08 string?
---@field hex09 string?
---@field hex10 string?

---@alias eyes.Highlights.Core "diagnostics"|"diff"|"editor"|"spell"|"syntax"|"terminal"|"treesitter"
---@alias eyes.Highlights.Plugins
---| "blink.cmp"
---| "codeium.nvim"
---| "flash.nvim"
---| "fzf-lua"
---| "indent-blankline.nvim"
---| "lazy.nvim"
---| "leap.nvim"
---| "mason.nvim"
---| "mini.clue"
---| "mini.files"
---| "mini.icons"
---| "mini.indentscope"
---| "mini.nvim"
---| "neo-tree.nvim"
---| "noice.nvim"
---| "nvim-cmp"
---| "nvim-dap-ui"
---| "nvim-notify"
---| "nvim-web-devicons"
---| "oil.nvim"
---| "render-markdown.nvim"
---| "snacks.nvim"
---| "telescope.nvim"
---| "undotree"
---| "vim-illuminate"

---@class eyes.Options
---@field transparent boolean
---@field highlights {
---  core: eyes.Highlights.Core[]|"all",
---  plugins: eyes.Highlights.Plugins[]|"all"|"auto",
---}
---@field extend {
--- highlights?: table<string, vim.api.keyset.highlight>,
--- palette?: eyes.Palette,
---}
