return {
	BlinkCmpMenu = "Pmenu",
	BlinkCmpMenuBorder = "FloatBorder",
	BlinkCmpMenuSelection = "PmenuSel",

	BlinkCmpScrollBarGutter = "PmenuSbar",
	BlinkCmpScrollBarThumb = "PmenuThumb",

	BlinkCmpLabel = "Pmenu",
	BlinkCmpLabelDeprecated = "Deprecated",
	BlinkCmpLabelDescription = "Pmenu",
	BlinkCmpLabelDetail = "Mute",
	BlinkCmpLabelMatch = "PmenuMatch",

	BlinkCmpKind = "Icon",
	BlinkCmpKindClass = "BlinkCmpKind",
	BlinkCmpKindColor = "BlinkCmpKind",
	BlinkCmpKindConstant = "BlinkCmpKind",
	BlinkCmpKindConstructor = "BlinkCmpKind",
	BlinkCmpKindEnum = "BlinkCmpKind",
	BlinkCmpKindEnumMember = "BlinkCmpKind",
	BlinkCmpKindEvent = "BlinkCmpKind",
	BlinkCmpKindField = "BlinkCmpKind",
	BlinkCmpKindFile = "BlinkCmpKind",
	BlinkCmpKindFolder = "BlinkCmpKind",
	BlinkCmpKindFunction = "BlinkCmpKind",
	BlinkCmpKindInterface = "BlinkCmpKind",
	BlinkCmpKindKeyword = "BlinkCmpKind",
	BlinkCmpKindMethod = "BlinkCmpKind",
	BlinkCmpKindModule = "BlinkCmpKind",
	BlinkCmpKindOperator = "BlinkCmpKind",
	BlinkCmpKindProperty = "BlinkCmpKind",
	BlinkCmpKindReference = "BlinkCmpKind",
	BlinkCmpKindSnippet = "BlinkCmpKind",
	BlinkCmpKindStruct = "BlinkCmpKind",
	BlinkCmpKindText = "BlinkCmpKind",
	BlinkCmpKindTypeParameter = "BlinkCmpKind",
	BlinkCmpKindUnit = "BlinkCmpKind",
	BlinkCmpKindValue = "BlinkCmpKind",
	BlinkCmpKindVariable = "BlinkCmpKind",

	BlinkCmpDoc = "NormalFloat",
	BlinkCmpDocBorder = "FloatBorder",
	BlinkCmpDocCursorLine = "CursorLine",
	BlinkCmpDocSeparator = "FloatBorder",

	BlinkCmpSignatureHelp = "NormalFloat",
	BlinkCmpSignatureHelpActiveParameter = "LspSignatureActiveParameter",
	BlinkCmpSignatureHelpBorder = "FloatBorder",

	BlinkCmpSource = "Dim",

	BlinkCmpGhostText = "Dim",
}
