return {
	NeoTreeBufferNumber = "Mute",
	NeoTreeCursorLine = "CursorLine",
	NeoTreeDimText = "Mute",
	NeoTreeDirectoryIcon = "Icon",
	NeoTreeDirectoryName = "Directory",
	NeoTreeDotfile = "Dim",
	NeoTreeEndOfBuffer = "EndOfBuffer",
	NeoTreeExpander = "Icon",
	NeoTreeFadeText1 = "Mute",
	NeoTreeFadeText2 = "Dim",
	NeoTreeFileIcon = "Icon",
	NeoTreeFileName = { fg = "fg" },
	NeoTreeFileNameOpened = { fg = "fg" },
	NeoTreeFileStats = { fg = "fg" },
	NeoTreeFileStatsHeader = "Title",
	NeoTreeFilterTerm = { fg = "fg" },
	NeoTreeFloatBorder = "FloatBorder",
	NeoTreeFloatNormal = "NormalFloat",
	NeoTreeFloatTitle = "FloatTitle",
	NeoTreeGitAdded = "Added",
	NeoTreeGitConflict = "Changed",
	NeoTreeGitDeleted = "Removed",
	NeoTreeGitIgnored = "Dim",
	NeoTreeGitModified = "Changed",
	NeoTreeGitRenamed = "Changed",
	NeoTreeGitStaged = "Added",
	NeoTreeGitUnstaged = "Dim",
	NeoTreeGitUntracked = "Dim",
	NeoTreeHiddenByName = "Dim",
	NeoTreeIndentMarker = "Whitespace",
	NeoTreeMessage = "Dim",
	NeoTreeModified = "Icon",
	NeoTreeNormal = "Normal",
	NeoTreeNormalNC = "NormalNC",
	NeoTreePreview = "Search",
	NeoTreeRootName = "Title",
	NeoTreeSignColumn = "SignColumn",
	NeoTreeStatusLine = "StatusLine",
	NeoTreeStatusLineNC = "StatusLineNC",
	NeoTreeSymbolicLinkTarget = "Mute",
	NeoTreeTabActive = "TabLineSel",
	NeoTreeTabInactive = "TabLine",
	NeoTreeTabSeparatorActive = "Border",
	NeoTreeTabSeparatorInactive = "Border",
	NeoTreeTitleBar = "Title",
	NeoTreeVertSplit = "VertSplit",
	NeoTreeWinSeparator = "WinSeparator",
	NeoTreeWindowsHidden = "Dim",
}
