return {
	NoiceCmdline = { fg = "fg" },
	NoiceCmdlinePrompt = { fg = "fg" },

	NoiceCmdlineIcon = "Icon",
	NoiceCmdlineIconCalculator = "Icon",
	NoiceCmdlineIconCmdline = "Icon",
	NoiceCmdlineIconFilter = "Icon",
	NoiceCmdlineIconHelp = "Icon",
	NoiceCmdlineIconInput = "Icon",
	NoiceCmdlineIconLua = "Icon",
	NoiceCmdlineIconSearch = "Icon",

	NoiceCmdlinePopup = "NormalFloat",
	NoiceCmdlinePopupBorder = "FloatBorder",
	NoiceCmdlinePopupBorderCalculator = "FloatBorder",
	NoiceCmdlinePopupBorderCmdline = "FloatBorder",
	NoiceCmdlinePopupBorderFilter = "FloatBorder",
	NoiceCmdlinePopupBorderHelp = "FloatBorder",
	NoiceCmdlinePopupBorderInput = "FloatBorder",
	NoiceCmdlinePopupBorderLua = "FloatBorder",
	NoiceCmdlinePopupBorderSearch = "FloatBorder",

	NoiceCmdlinePopupTitle = "FloatTitle",
	NoiceCmdlinePopupTitleCalculator = "FloatTitle",
	NoiceCmdlinePopupTitleCmdline = "FloatTitle",
	NoiceCmdlinePopupTitleFilter = "FloatTitle",
	NoiceCmdlinePopupTitleHelp = "FloatTitle",
	NoiceCmdlinePopupTitleInput = "FloatTitle",
	NoiceCmdlinePopupTitleLua = "FloatTitle",
	NoiceCmdlinePopupTitleSearch = "FloatTitle",

	NoiceCompletionItemKindDefault = { fg = "fg" },
	NoiceCompletionItemKindClass = { fg = "fg" },
	NoiceCompletionItemKindColor = { fg = "fg" },
	NoiceCompletionItemKindConstant = { fg = "fg" },
	NoiceCompletionItemKindConstructor = { fg = "fg" },
	NoiceCompletionItemKindEnum = { fg = "fg" },
	NoiceCompletionItemKindEnumMember = { fg = "fg" },
	NoiceCompletionItemKindField = { fg = "fg" },
	NoiceCompletionItemKindFile = { fg = "fg" },
	NoiceCompletionItemKindFolder = { fg = "fg" },
	NoiceCompletionItemKindFunction = { fg = "fg" },
	NoiceCompletionItemKindInterface = { fg = "fg" },
	NoiceCompletionItemKindKeyword = { fg = "fg" },
	NoiceCompletionItemKindMethod = { fg = "fg" },
	NoiceCompletionItemKindModule = { fg = "fg" },
	NoiceCompletionItemKindProperty = { fg = "fg" },
	NoiceCompletionItemKindSnippet = { fg = "fg" },
	NoiceCompletionItemKindStruct = { fg = "fg" },
	NoiceCompletionItemKindText = { fg = "fg" },
	NoiceCompletionItemKindUnit = { fg = "fg" },
	NoiceCompletionItemKindValue = { fg = "fg" },
	NoiceCompletionItemKindVariable = { fg = "fg" },

	NoiceConfirm = "NormalFloat",
	NoiceConfirmBorder = "FloatBorder",
	NoiceFormatConfirm = "Mute",
	NoiceFormatConfirmDefault = "Title",

	NoiceCursor = "Cursor",

	NoiceFormatDate = "Mute",
	NoiceFormatEvent = "NonText",
	NoiceFormatKind = "NonText",
	NoiceFormatTitle = "Title",

	NoiceFormatLevelOff = "NonText",
	NoiceFormatLevelDebug = "NonText",
	NoiceFormatLevelTrace = "NonText",
	NoiceFormatLevelError = "DiagnosticVirtualTextError",
	NoiceFormatLevelInfo = "DiagnosticVirtualTextInfo",
	NoiceFormatLevelWarn = "DiagnosticVirtualTextWarn",

	NoiceHiddenCursor = { blend = 100 },

	NoiceLspProgressClient = "Title",
	NoiceLspProgressSpinner = { fg = "fg" },
	NoiceLspProgressTitle = { fg = "fg" },
	NoiceFormatProgressDone = { reverse = true },
	NoiceFormatProgressTodo = "Normal",

	NoiceMini = { fg = "fg" },

	NoicePopup = "NormalFloat",
	NoicePopupBorder = "FloatBorder",
	NoicePopupmenu = "Pmenu",
	NoicePopupmenuBorder = "FloatBorder",
	NoicePopupmenuMatch = "PmenuMatch",
	NoicePopupmenuSelected = "PmenuSel",

	NoiceScrollbar = "PmenuSbar",
	NoiceScrollbarThumb = "PmenuThumb",

	NoiceSplit = "NormalFloat",
	NoiceSplitBorder = "FloatBorder",

	NoiceVirtualText = "Dim",
}
