return {
	CmpItemAbbr = "Pmenu",
	CmpItemAbbrDeprecated = "Deprecated",
	CmpItemAbbrMatch = "PmenuMatch",
	CmpItemAbbrMatchFuzzy = "PmenuMatch",

	CmpItemMenu = "Mute",

	CmpItemKind = "Icon",
	CmpItemKindClass = "CmpItemKind",
	CmpItemKindColor = "CmpItemKind",
	CmpItemKindConstant = "CmpItemKind",
	CmpItemKindConstructor = "CmpItemKind",
	CmpItemKindEnum = "CmpItemKind",
	CmpItemKindEnumMember = "CmpItemKind",
	CmpItemKindEvent = "CmpItemKind",
	CmpItemKindField = "CmpItemKind",
	CmpItemKindFile = "CmpItemKind",
	CmpItemKindFolder = "CmpItemKind",
	CmpItemKindFunction = "CmpItemKind",
	CmpItemKindInterface = "CmpItemKind",
	CmpItemKindKeyword = "CmpItemKind",
	CmpItemKindMethod = "CmpItemKind",
	CmpItemKindModule = "CmpItemKind",
	CmpItemKindOperator = "CmpItemKind",
	CmpItemKindProperty = "CmpItemKind",
	CmpItemKindReference = "CmpItemKind",
	CmpItemKindSnippet = "CmpItemKind",
	CmpItemKindStruct = "CmpItemKind",
	CmpItemKindText = "CmpItemKind",
	CmpItemKindTypeParameter = "CmpItemKind",
	CmpItemKindUnit = "CmpItemKind",
	CmpItemKindValue = "CmpItemKind",
	CmpItemKindVariable = "CmpItemKind",

	CmpGhostText = { link = "Dim" },
}
