local palette = require("eyes.palette")

return {
	SnacksDashboardNormal = "Normal",
	SnacksDashboardHeader = { fg = "fg" },
	SnacksDashboardFooter = { fg = "fg" },
	SnacksDashboardTitle = "Title",
	SnacksDashboardTerminal = "None",
	SnacksDashboardIcon = "Icon",
	SnacksDashboardDesc = { fg = "fg" },
	SnacksDashboardKey = "Mute",
	SnacksDashboardDir = "Directory",
	SnacksDashboardFile = { fg = "fg" },
	SnacksDashboardSpecial = "Mute",

	SnacksIndent = "Whitespace",
	SnacksIndent1 = { fg = palette.hex01 },
	SnacksIndent2 = { fg = palette.hex02 },
	SnacksIndent3 = { fg = palette.hex03 },
	SnacksIndent4 = { fg = palette.hex04 },
	SnacksIndent5 = { fg = palette.hex05 },
	SnacksIndent6 = { fg = palette.hex06 },
	SnacksIndent7 = { fg = palette.hex07 },
	SnacksIndent8 = { fg = palette.hex08 },
	SnacksIndentBlank = "Dim",
	SnacksIndentChunk = "Mute",
	SnacksIndentScope = "Mute",

	SnacksInputNormal = "NormalFloat",
	SnacksInputBorder = "FloatBorder",
	SnacksInputTitle = "FloatTitle",
	SnacksInputPrompt = "FloatTitle",
	SnacksInputIcon = "Icon",

	SnacksNotifierMinimal = "NormalFloat",

	SnacksNotifierError = "NormalFloat",
	SnacksNotifierTitleError = "DiagnosticError",
	SnacksNotifierFooterError = "DiagnosticError",
	SnacksNotifierBorderError = "FloatBorder",
	SnacksNotifierIconError = "DiagnosticSignError",

	SnacksNotifierWarn = "NormalFloat",
	SnacksNotifierTitleWarn = "DiagnosticWarn",
	SnacksNotifierFooterWarn = "DiagnosticWarn",
	SnacksNotifierBorderWarn = "FloatBorder",
	SnacksNotifierIconWarn = "DiagnosticSignWarn",

	SnacksNotifierInfo = "NormalFloat",
	SnacksNotifierTitleInfo = "DiagnosticInfo",
	SnacksNotifierFooterInfo = "DiagnosticInfo",
	SnacksNotifierBorderInfo = "FloatBorder",
	SnacksNotifierIconInfo = "DiagnosticSignInfo",

	SnacksNotifierDebug = "NormalFloat",
	SnacksNotifierTitleDebug = "NonText",
	SnacksNotifierFooterDebug = "NonText",
	SnacksNotifierBorderDebug = "FloatBorder",
	SnacksNotifierIconDebug = "NonText",

	SnacksNotifierTrace = "NormalFloat",
	SnacksNotifierTitleTrace = "NonText",
	SnacksNotifierFooterTrace = "NonText",
	SnacksNotifierBorderTrace = "FloatBorder",
	SnacksNotifierIconTrace = "NonText",

	SnacksNotifierHistory = "NormalFloat",
	SnacksNotifierHistoryTitle = "FloatTitle",
	SnacksNotifierHistoryDateTime = "Mute",

	SnacksPicker = "NormalFloat",
	SnacksPickerTitle = "FloatTitle",
	SnacksPickerBorder = "FloatBorder",
	FloatFooter = "FloatFooter",
	SnacksPickerCursorLine = "CursorLine",

	SnacksPickerInput = "NormalFloat",
	SnacksPickerInputTitle = "FloatTitle",
	SnacksPickerInputBorder = "FloatBorder",
	SnacksPickerInputFooter = "FloatFooter",
	SnacksPickerInputCursorLine = "CursorLine",
	SnacksPickerInputSearch = "Search",
	SnacksPickerPrompt = "Mute",

	SnacksPickerPreview = "NormalFloat",
	SnacksPickerPreviewTitle = "FloatTitle",
	SnacksPickerPreviewBorder = "FloatBorder",
	SnacksPickerPreviewFooter = "FloatFooter",
	SnacksPickerPreviewCursorLine = "CursorLine",

	SnacksPickerList = "NormalFloat",
	SnacksPickerListTitle = "FloatTitle",
	SnacksPickerListBorder = "FloatBorder",
	SnacksPickerListFooter = "FloatFooter",
	SnacksPickerListCursorLine = "CursorLine",

	SnacksPickerBox = "NormalFloat",
	SnacksPickerBoxTitle = "FloatTitle",
	SnacksPickerBoxBorder = "FloatBorder",
	SnacksPickerBoxFooter = "FloatFooter",
	SnacksPickerBoxCursorLine = "CursorLine",

	SnacksPickerToggle = "Mute",
	SnacksPickerToggleFollow = "Mute",
	SnacksPickerToggleHidden = "Mute",
	SnacksPickerToggleIgnored = "Mute",
	SnacksPickerToggleModified = "Mute",
	SnacksPickerToggleRegex = "Mute",

	SnacksPickerSelected = { fg = "fg" },
	SnacksPickerUnselected = "Dim",

	SnacksPickerSpinner = "Dim",
	SnacksPickerTotals = "Dim",

	SnacksPickerSearch = "Search",
	SnacksPickerMatch = "PmenuMatch",

	SnacksPickerTime = "Mute",
	SnacksPickerTree = "Dim",
	SnacksPickerIdx = "Mute",
	SnacksPickerCode = "@markup.raw.markdown_inline",

	SnacksPickerBold = "Bold",
	SnacksPickerComment = "Comment",
	SnacksPickerDelim = "Delimiter",
	SnacksPickerDimmed = "Dim",
	SnacksPickerItalic = "Italic",
	SnacksPickerSpecial = "Special",

	SnacksPickerFile = { fg = "fg" },
	SnacksPickerDirectory = "Directory",
	SnacksPickerDir = "Directory",
	SnacksPickerLink = "Mute",
	SnacksPickerLinkBroken = "Deprecated",
	SnacksPickerPathHidden = "Dim",
	SnacksPickerPathIgnored = "Dim",
	SnacksPickerLabel = "Mute",
	SnacksPickerRow = "Mute",
	SnacksPickerCol = "Mute",

	SnacksPickerIconArray = "Icon",
	SnacksPickerIconBoolean = "Icon",
	SnacksPickerIconClass = "Icon",
	SnacksPickerIconConstant = "Icon",
	SnacksPickerIconConstructor = "Icon",
	SnacksPickerIconEnum = "Icon",
	SnacksPickerIconEnumMember = "Icon",
	SnacksPickerIconEvent = "Icon",
	SnacksPickerIconField = "Icon",
	SnacksPickerIconFile = "Icon",
	SnacksPickerIconFunction = "Icon",
	SnacksPickerIconInterface = "Icon",
	SnacksPickerIconKey = "Icon",
	SnacksPickerIconMethod = "Icon",
	SnacksPickerIconModule = "Icon",
	SnacksPickerIconNamespace = "Icon",
	SnacksPickerIconNull = "Icon",
	SnacksPickerIconNumber = "Icon",
	SnacksPickerIconObject = "Icon",
	SnacksPickerIconOperator = "Icon",
	SnacksPickerIconPackage = "Icon",
	SnacksPickerIconProperty = "Icon",
	SnacksPickerIconString = "Icon",
	SnacksPickerIconStruct = "Icon",
	SnacksPickerIconTypeParameter = "Icon",
	SnacksPickerIconVariable = "Icon",

	SnacksPickerAuEvent = "Mute",
	SnacksPickerAuGroup = { fg = "fg" },
	SnacksPickerAuPattern = "Mute",

	SnacksPickerBufFlags = "Mute",
	SnacksPickerBufNr = "Mute",

	SnacksPickerCmd = { fg = "fg" },
	SnacksPickerCmdBuiltin = { fg = "fg" },
	SnacksPickerDesc = "Mute",

	SnacksPickerDiagnosticCode = "Mute",
	SnacksPickerDiagnosticSource = "Dim",

	SnacksPickerGitBranch = { fg = "fg" },
	SnacksPickerGitBranchCurrent = { fg = "fg" },
	SnacksPickerGitDetached = { fg = "fg" },

	SnacksPickerGitBreaking = "Error",
	SnacksPickerGitCommit = "Mute",
	SnacksPickerGitDate = "Mute",
	SnacksPickerGitIssue = "Mute",
	SnacksPickerGitScope = "Italic",
	SnacksPickerGitType = "Bold",

	SnacksPickerGitStatus = "Mute",
	SnacksPickerGitStatusAdded = "Added",
	SnacksPickerGitStatusCopied = "Added",
	SnacksPickerGitStatusDeleted = "Removed",
	SnacksPickerGitStatusIgnored = "Dim",
	SnacksPickerGitStatusModified = "Changed",
	SnacksPickerGitStatusRenamed = "Changed",
	SnacksPickerGitStatusStaged = "Added",
	SnacksPickerGitStatusUnmerged = "Dim",
	SnacksPickerGitStatusUntracked = "Dim",

	SnacksPickerIcon = "Icon",
	SnacksPickerIconCategory = "Mute",
	SnacksPickerIconName = { fg = "fg" },
	SnacksPickerIconSource = "Mute",

	SnacksPickerKeymapLhs = "Mute",
	SnacksPickerKeymapMode = "Mute",
	SnacksPickerKeymapNowait = "Mute",
	SnacksPickerKeymapRhs = "Mute",

	SnacksPickerManPage = "Mute",
	SnacksPickerManSection = "Mute",

	SnacksPickerPickWin = "Search",
	SnacksPickerPickWinCurrent = "CurSearch",

	SnacksPickerRegister = "Mute",

	SnacksPickerUndoAdded = "Added",
	SnacksPickerUndoCurrent = { fg = "fg" },
	SnacksPickerUndoRemoved = "Removed",
	SnacksPickerUndoSaved = "Mute",

	SnacksStatusColumnMark = { fg = "fg" },

	SnacksNormal = "Normal",
	SnacksNormalNC = "NormalNC",
	SnacksBackdrop = { bg = "black" },
	SnacksWinBar = "WinBar",
	SnacksWinBarNC = "WinBarNC",
	SnacksWinKey = "Mute",
	SnacksWinKeyDesc = { fg = "fg" },
	SnacksWinKeySep = "Mute",
}
