local M = {}

local utility = require("eyes.utility")
local hl = utility.hl
local extend = utility.extend

M.setup = function()
	hl("TelescopeNormal", { link = "Normal" })
	hl("TelescopeTitle", { link = "Title" })
	hl("TelescopeBorder", { link = "Border" })
	hl("TelescopeMatching", { link = "PmenuMatch" })

	hl("TelescopeSelection", { link = "CursorColumn" })
	hl("TelescopeSelectionCaret", extend("CursorColumn", { fg = "fg" }))
	hl("TelescopeMultiIcon", { fg = "fg" })
	hl("TelescopeMultiSelection", { fg = "fg" })

	hl("TelescopePromptNormal", { link = "TelescopeNormal" })
	hl("TelescopePromptTitle", { link = "TelescopeTitle" })
	hl("TelescopePromptBorder", { link = "TelescopeBorder" })
	hl("TelescopePromptCounter", { link = "Dim" })
	hl("TelescopePromptPrefix", { fg = "fg" })

	hl("TelescopeResultsNormal", { link = "TelescopeNormal" })
	hl("TelescopeResultsTitle", { link = "TelescopeTitle" })
	hl("TelescopeResultsBorder", { link = "TelescopeBorder" })
	hl("TelescopeResultsClass", { link = "Type" })
	hl("TelescopeResultsComment", { link = "Comment" })
	hl("TelescopeResultsConstant", { link = "Constant" })
	hl("TelescopeResultsDiffAdd", { link = "DiffAdd" })
	hl("TelescopeResultsDiffChange", { link = "DiffChange" })
	hl("TelescopeResultsDiffDelete", { link = "DiffDelete" })
	hl("TelescopeResultsDiffUntracked", { fg = "fg" })
	hl("TelescopeResultsField", { link = "@attribute" })
	hl("TelescopeResultsFunction", { link = "Function" })
	hl("TelescopeResultsIdentifier", { link = "Identifier" })
	hl("TelescopeResultsLineNr", { link = "LineNr" })
	hl("TelescopeResultsMethod", { link = "Function" })
	hl("TelescopeResultsNumber", { link = "Constant" })
	hl("TelescopeResultsOperator", { link = "Operator" })
	hl("TelescopeResultsSpecialComment", { link = "SpecialComment" })
	hl("TelescopeResultsStruct", { link = "Structure" })
	hl("TelescopeResultsVariable", { link = "Identifier" })

	hl("TelescopePreviewNormal", { link = "TelescopeNormal" })
	hl("TelescopePreviewTitle", { link = "TelescopeTitle" })
	hl("TelescopePreviewBorder", { link = "TelescopeBorder" })
	hl("TelescopePreviewLine", { link = "Visual" })
	hl("TelescopePreviewMatch", { link = "Search" })
	hl("TelescopePreviewMessage", { link = "TelescopePreviewNormal" })
	hl("TelescopePreviewMessageFillchar", { link = "TelescopePreviewMessage" })
	hl("TelescopePreviewBlock", { fg = "fg" })
	hl("TelescopePreviewCharDev", { fg = "fg" })
	hl("TelescopePreviewDate", { fg = "fg" })
	hl("TelescopePreviewDirectory", { link = "Directory" })
	hl("TelescopePreviewExecute", { fg = "fg" })
	hl("TelescopePreviewGroup", { fg = "fg" })
	hl("TelescopePreviewHyphen", { fg = "fg" })
	hl("TelescopePreviewLink", { fg = "fg" })
	hl("TelescopePreviewPipe", { fg = "fg" })
	hl("TelescopePreviewRead", { fg = "fg" })
	hl("TelescopePreviewSize", { fg = "fg" })
	hl("TelescopePreviewSocket", { fg = "fg" })
	hl("TelescopePreviewSticky", { fg = "fg" })
	hl("TelescopePreviewUser", { fg = "fg" })
	hl("TelescopePreviewWrite", { fg = "fg" })
end

return M
