local M = {}

local utility = require("eyes.utility")
local hl = utility.hl
local extend = utility.extend

M.setup = function()
	hl("TelescopeNormal", "Normal")
	hl("TelescopeTitle", "Title")
	hl("TelescopeBorder", "Border")
	hl("TelescopeMatching", "PmenuMatch")

	hl("TelescopeSelection", "CursorColumn")
	hl("TelescopeSelectionCaret", extend("CursorColumn", { fg = "fg" }))
	hl("TelescopeMultiIcon", { fg = "fg" })
	hl("TelescopeMultiSelection", { fg = "fg" })

	hl("TelescopePromptNormal", "TelescopeNormal")
	hl("TelescopePromptTitle", "TelescopeTitle")
	hl("TelescopePromptBorder", "TelescopeBorder")
	hl("TelescopePromptCounter", "Dim")
	hl("TelescopePromptPrefix", { fg = "fg" })

	hl("TelescopeResultsNormal", "TelescopeNormal")
	hl("TelescopeResultsTitle", "TelescopeTitle")
	hl("TelescopeResultsBorder", "TelescopeBorder")
	hl("TelescopeResultsClass", "Type")
	hl("TelescopeResultsComment", "Comment")
	hl("TelescopeResultsConstant", "Constant")
	hl("TelescopeResultsDiffAdd", "DiffAdd")
	hl("TelescopeResultsDiffChange", "DiffChange")
	hl("TelescopeResultsDiffDelete", "DiffDelete")
	hl("TelescopeResultsDiffUntracked", { fg = "fg" })
	hl("TelescopeResultsField", "@attribute")
	hl("TelescopeResultsFunction", "Function")
	hl("TelescopeResultsIdentifier", "Identifier")
	hl("TelescopeResultsLineNr", "LineNr")
	hl("TelescopeResultsMethod", "Function")
	hl("TelescopeResultsNumber", "Constant")
	hl("TelescopeResultsOperator", "Operator")
	hl("TelescopeResultsSpecialComment", "SpecialComment")
	hl("TelescopeResultsStruct", "Structure")
	hl("TelescopeResultsVariable", "Identifier")

	hl("TelescopePreviewNormal", "TelescopeNormal")
	hl("TelescopePreviewTitle", "TelescopeTitle")
	hl("TelescopePreviewBorder", "TelescopeBorder")
	hl("TelescopePreviewLine", "Visual")
	hl("TelescopePreviewMatch", "Search")
	hl("TelescopePreviewMessage", "TelescopePreviewNormal")
	hl("TelescopePreviewMessageFillchar", "TelescopePreviewMessage")
	hl("TelescopePreviewBlock", { fg = "fg" })
	hl("TelescopePreviewCharDev", { fg = "fg" })
	hl("TelescopePreviewDate", { fg = "fg" })
	hl("TelescopePreviewDirectory", "Directory")
	hl("TelescopePreviewExecute", { fg = "fg" })
	hl("TelescopePreviewGroup", { fg = "fg" })
	hl("TelescopePreviewHyphen", { fg = "fg" })
	hl("TelescopePreviewLink", { fg = "fg" })
	hl("TelescopePreviewPipe", { fg = "fg" })
	hl("TelescopePreviewRead", { fg = "fg" })
	hl("TelescopePreviewSize", { fg = "fg" })
	hl("TelescopePreviewSocket", { fg = "fg" })
	hl("TelescopePreviewSticky", { fg = "fg" })
	hl("TelescopePreviewUser", { fg = "fg" })
	hl("TelescopePreviewWrite", { fg = "fg" })
end

return M
