return {
	TelescopeNormal = "NormalFloat",
	TelescopeTitle = "FloatTitle",
	TelescopeBorder = "FloatBorder",
	TelescopeMatching = "PmenuMatch",

	TelescopeSelection = "CursorColumn",
	TelescopeSelectionCaret = "CursorColumn",
	TelescopeMultiIcon = "Icon",
	TelescopeMultiSelection = "None",

	TelescopePromptNormal = "NormalFloat",
	TelescopePromptTitle = "FloatTitle",
	TelescopePromptBorder = "FloatBorder",
	TelescopePromptCounter = "Dim",
	TelescopePromptPrefix = "Mute",

	TelescopeResultsNormal = "NormalFloat",
	TelescopeResultsTitle = "FloatTitle",
	TelescopeResultsBorder = "FloatBorder",
	TelescopeResultsClass = "@type",
	TelescopeResultsComment = "@comment",
	TelescopeResultsConstant = "@constant",
	TelescopeResultsDiffAdd = "DiffAdd",
	TelescopeResultsDiffChange = "DiffChange",
	TelescopeResultsDiffDelete = "DiffDelete",
	TelescopeResultsDiffUntracked = "Dim",
	TelescopeResultsField = "@attribute",
	TelescopeResultsFunction = "@function",
	TelescopeResultsIdentifier = "@variable",
	TelescopeResultsLineNr = "LineNr",
	TelescopeResultsMethod = "@function.method",
	TelescopeResultsNumber = "@number",
	TelescopeResultsOperator = "@operator",
	TelescopeResultsSpecialComment = "@comment",
	TelescopeResultsStruct = "@type",
	TelescopeResultsVariable = "@variable",

	TelescopePreviewNormal = "NormalFloat",
	TelescopePreviewTitle = "FloatTitle",
	TelescopePreviewBorder = "FloatBorder",
	TelescopePreviewLine = "Visual",
	TelescopePreviewMatch = "Search",
	TelescopePreviewMessage = { fg = "fg" },
	TelescopePreviewMessageFillchar = { fg = "fg" },
	TelescopePreviewBlock = { fg = "fg" },
	TelescopePreviewCharDev = { fg = "fg" },
	TelescopePreviewDate = { fg = "fg" },
	TelescopePreviewDirectory = "Directory",
	TelescopePreviewExecute = { fg = "fg" },
	TelescopePreviewGroup = { fg = "fg" },
	TelescopePreviewHyphen = { fg = "fg" },
	TelescopePreviewLink = { fg = "fg" },
	TelescopePreviewPipe = { fg = "fg" },
	TelescopePreviewRead = { fg = "fg" },
	TelescopePreviewSize = { fg = "fg" },
	TelescopePreviewSocket = { fg = "fg" },
	TelescopePreviewSticky = { fg = "fg" },
	TelescopePreviewUser = { fg = "fg" },
	TelescopePreviewWrite = { fg = "fg" },
}
