local M = {}

local hl = require("eyes.utility").hl

M.setup = function()
	hl("TelescopeNormal", "NormalFloat")
	hl("TelescopeTitle", "FloatTitle")
	hl("TelescopeBorder", "FloatBorder")
	hl("TelescopeMatching", "PmenuMatch")

	hl("TelescopeSelection", "CursorColumn")
	hl("TelescopeSelectionCaret", "CursorColumn")
	hl("TelescopeMultiIcon", "Icon")
	hl("TelescopeMultiSelection", "None")

	hl("TelescopePromptNormal", "NormalFloat")
	hl("TelescopePromptTitle", "FloatTitle")
	hl("TelescopePromptBorder", "FloatBorder")
	hl("TelescopePromptCounter", "Dim")
	hl("TelescopePromptPrefix", "Mute")

	hl("TelescopeResultsNormal", "NormalFloat")
	hl("TelescopeResultsTitle", "FloatTitle")
	hl("TelescopeResultsBorder", "FloatBorder")
	hl("TelescopeResultsClass", "@type")
	hl("TelescopeResultsComment", "@comment")
	hl("TelescopeResultsConstant", "@constant")
	hl("TelescopeResultsDiffAdd", "DiffAdd")
	hl("TelescopeResultsDiffChange", "DiffChange")
	hl("TelescopeResultsDiffDelete", "DiffDelete")
	hl("TelescopeResultsDiffUntracked", "Dim")
	hl("TelescopeResultsField", "@attribute")
	hl("TelescopeResultsFunction", "@function")
	hl("TelescopeResultsIdentifier", "@variable")
	hl("TelescopeResultsLineNr", "LineNr")
	hl("TelescopeResultsMethod", "@function.method")
	hl("TelescopeResultsNumber", "@number")
	hl("TelescopeResultsOperator", "@operator")
	hl("TelescopeResultsSpecialComment", "@comment")
	hl("TelescopeResultsStruct", "@type")
	hl("TelescopeResultsVariable", "@variable")

	hl("TelescopePreviewNormal", "NormalFloat")
	hl("TelescopePreviewTitle", "FloatTitle")
	hl("TelescopePreviewBorder", "FloatBorder")
	hl("TelescopePreviewLine", "Visual")
	hl("TelescopePreviewMatch", "Search")
	hl("TelescopePreviewMessage", { fg = "fg" })
	hl("TelescopePreviewMessageFillchar", { fg = "fg" })
	hl("TelescopePreviewBlock", { fg = "fg" })
	hl("TelescopePreviewCharDev", { fg = "fg" })
	hl("TelescopePreviewDate", { fg = "fg" })
	hl("TelescopePreviewDirectory", "Directory")
	hl("TelescopePreviewExecute", { fg = "fg" })
	hl("TelescopePreviewGroup", { fg = "fg" })
	hl("TelescopePreviewHyphen", { fg = "fg" })
	hl("TelescopePreviewLink", { fg = "fg" })
	hl("TelescopePreviewPipe", { fg = "fg" })
	hl("TelescopePreviewRead", { fg = "fg" })
	hl("TelescopePreviewSize", { fg = "fg" })
	hl("TelescopePreviewSocket", { fg = "fg" })
	hl("TelescopePreviewSticky", { fg = "fg" })
	hl("TelescopePreviewUser", { fg = "fg" })
	hl("TelescopePreviewWrite", { fg = "fg" })
end

return M
