return {
	UndotreeBranch = "Mute",
	UndotreeCurrent = { fg = "fg" },
	UndotreeFirstNode = "Mute",
	UndotreeHead = "Mute",
	UndotreeHelp = "Dim",
	UndotreeHelpKey = { fg = "fg" },
	UndotreeHelpTitle = "Title",
	UndotreeNext = "Mute",
	UndotreeNode = "Mute",
	UndotreeNodeCurrent = { fg = "fg" },
	UndotreeSavedBig = "Bold",
	UndotreeSavedSmall = { fg = "fg" },
	UndotreeSeq = "Dim",
	UndotreeTimeStamp = "Mute",
}
